version: '2'
services:
  influx:
    image: influxdb:1.0.0-alpine
    volumes:
        - /var/lib/influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
  db:
    image: mongo:3
    entrypoint: [ "mongod", "--smallfiles", "--rest" ]
    expose:
      - "27017"
    ports:
      - "27017:27017"
