
web:
  build: .
  command: npm start
  environment:
    USE_LOCAL_REPO: 'true'
    PORT: 2426
    MONGODB_URL: 'mongodb://db:27017/fuse-features-api'
    MONGODB_OPLOG: 'mongodb://db:27017/local'
    NODE_ENV: 'dev'
    NPM_CONFIG_PRODUCTION: 'false'    
  ports:
    - "2426:2426"
  links:
    - db
