version: '2'
services:
  influx:
    image: influxdb:1.0.0-alpine
    volumes:
        - /var/lib/influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
  grafana:
    image: grafana/grafana:3.1.1
    ports:
      - "3000:3000"
